version: "3.9"
services:
  server:
    build: ./HRPolicyDepartment-backend
    ports:
      - "5001:5001"
    depends_on:
      - mysqldb
    networks:
      - hrpolicydepartment

  client:
    build:
      context: ./HRPolicyDepartment-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - server
    networks:
      - hrpolicydepartment

  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrpolicydepartment
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hrpolicydepartment

volumes:
  db_data:

networks:
  hrpolicydepartment:
